version: "3"

services:

  purl_fyi:
    build: .
    expose:
      - 8000

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - purl_fyi
